site_name: 'Backstage'
site_description: 'Main documentation for Backstage features and platform APIs'

theme: material

nav:
  - Overview:
      - What is Backstage?: README.md
      - Introduction: 'overview/introduction.md'
      - Architecture and concepts: 'overview/arch-and-concepts.md'
  - Getting started:
      - Overview: 'getting-started/index.md'
      - Installation: 'getting-started/installation.md'
      - Local development: 'getting-started/local-development.md'
      - Demo deployment: https://demo.backstage.io
      - Production deployments:
          - Create an App: 'getting-started/create-app.md'
          - App configuration:
              - Configuring App with plugins: 'getting-started/configure-app-with-plugins.md'
              - Customize the look-and-feel of your App: 'getting-started/customize-app-look-and-feel.md'
          - Deployment scenarios:
              - Kubernetes: 'getting-started/deployment-k8s.md'
              - Other: 'getting-started/deployment-other.md'
  - Features:
      - Software Catalog:
          - Overview: 'features/software-catalog/index.md'
          - System model: 'features/software-catalog/system-model.md'
          - YAML File Format: 'features/software-catalog/descriptor-format.md'
          - Populating the catalog: 'features/software-catalog/populating.md'
          - Extending the model: 'features/software-catalog/extending-the-model.md'
          - External integrations: 'features/software-catalog/external-integrations.md'
          - API: 'features/software-catalog/api.md'
      - Software creation templates:
          - Overview: 'features/software-templates/index.md'
          - Configure templates: 'features/software-templates/configure-templates.md'
          - Adding templates: 'features/software-templates/adding-templates.md'
      - Docs-like-code:
          - Overview: 'features/techdocs/README.md'
          - Getting Started: 'features/techdocs/getting-started.md'
          - Concepts: 'features/techdocs/concepts.md'
          - Reading Documentation: 'features/techdocs/reading-documentation.md'
          - Writing Documentation: 'features/techdocs/writing-documentation.md'
          - Publishing Documentation: 'features/techdocs/publishing-documentation.md'
          - Contributing: 'features/techdocs/contributing.md'
          - Debugging: 'features/techdocs/debugging.md'
          - FAQ: 'features/techdocs/FAQ.md'
  - Plugins:
      - Overview: 'plugins/index.md'
      - Existing plugins: 'plugins/existing-plugins.md'
      - Creating a new plugin: 'plugins/create-a-plugin.md'
      - Developing a plugin: 'plugins/developing-plugins.md'
      - Structure of a plugin: 'plugins/structure-of-a-plugin.md'
      - Backends and APIs:
          - Proxying: 'plugins/proxying.md'
          - Backstage backend plugin: 'plugins/proxying.md'
          - Call existing API: 'plugins/call-existing-api.md'
      - Testing:
          - Overview: 'plugins/testing.md'
      - Publishing:
          - Open source and NPM: 'plugins/publish-open-source.md'
          - Private/internal (non-open source): 'plugins/publish-private.md'
  - Authentication and identity:
      - Overview: 'auth/index.md'
      - Add auth provider: 'auth/add-auth-provider.md'
      - Auth backend: 'auth/auth-backend.md'
      - OAuth: 'auth/oauth.md'
      - Glossary: 'auth/glossary.md'
  - Designing for Backstage:
      - Overview: 'dls/index.md'
      - Backstage Design Language System (DLS): 'dls/design.md'
      - Storybook -- reusable UI components: 'dls/storybook.md'
      - Figma resources: 'dls/figma.md'
  - API references:
      - JavaScript/TypeScript API: 'api/javascript.md'
      - Backend APIs: 'api/backend.md'
  - Tutorials:
      - Overview: 'tutorials/index.md'
  - Architecture Decision Records (ADRs):
      - Overview: 'architecture-decisions/index.md' # TODO: Add all ADRs to the nav.
  - Contribute: contribute.md
  - Support: support.md
  - FAQ: FAQ.md
